In [4]:
print("Hello Talib")

Hello Talib

# Data Extract

In [5]:
import oracledb

conn = oracledb.connect(
    user = "hr",
    password = "hr",
    host = "192.168.101.190",
    port = 1521,
    service_name = "finiprm"
)
cur = conn.cursor()
print("connected ")

connected

In [6]:
cur.execute("""
        SELECT table_name
            from all_tables
            where owner = 'HR'
            """
)

for t in cur.fetchall():
    print(t[0])

REGIONS
COUNTRIES
LOCATIONS
DEPARTMENTS
JOBS
EMPLOYEES
JOB_HISTORY
TALIB
EMP1
GLOBAL_SUPERSTORE2
DATES
PAYMENTS
CUSTOMERS

In [7]:
import pandas as pd 

query = "select * from GLOBAL_SUPERSTORE2"
df = pd.read_sql(query, conn)

C:\Users\Work\AppData\Local\Temp\ipykernel_14152\2390321081.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [8]:
df.head()

,ROW_ID,ORDER_ID,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,CUSTOMER_NAME,SEGMENT,POSTAL_CODE,CITY,...,PRODUCT_ID,CATEGORY,SUB_CATEGORY,PRODUCT_NAME,SALES,QUANTITY,DISCOUNT,PROFIT,SHIPPING_COST,ORDER_PRIORITY
0,11743,IT-2014-VM2168591-41711,3/13/2014,3/13/2014,Same Day,VM-2168591,Valerie Mitchum,Home Office,NaN,Bergen op Zoom,...,FUR-CH-5442,Furniture,Chairs,"Office Star Executive Leather Armchair, Black","$2,570.87",11,0.5,"-$2,211.17",520.89,High
1,32648,CA-2014-AS10045140-41727,3/29/2014,4/1/2014,First Class,AS-100451408,Aaron Smayling,Corporate,22204,Arlington,...,OFF-ST-4516,Office Supplies,Storage,Hanging Personal Folder File,$31.40,2,0,$7.85,3.81,Medium
2,17522,ES-2013-DM1352548-41369,4/5/2013,4/5/2013,Same Day,DM-1352548,Don Miller,Corporate,NaN,Hanover,...,TEC-PH-3149,Technology,Phones,"Apple Smart Phone, with Caller ID","$2,875.77",9,0.5,"-$1,783.08",516.63,High
3,14721,ES-2013-NM18520120-41634,12/26/2013,12/28/2013,Second Class,NM-18520120,Neoma Murray,Consumer,NaN,Vigo,...,FUR-BO-5948,Furniture,Bookcases,"Sauder Classic Bookcase, Metal","$1,741.80",4,0,$261.24,515.24,Critical
4,29629,IN-2014-LC168857-41747,4/18/2014,4/19/2014,First Class,LC-168857,Lena Creighton,Consumer,NaN,Sydney,...,TEC-CO-6012,Technology,Copiers,"Sharp Wireless Fax, Laser","$1,601.64",5,0.1,$587.19,511.47,Critical

In [10]:
df.sort_values(by='ORDER_ID', ascending=False)

,ROW_ID,ORDER_ID,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,CUSTOMER_NAME,SEGMENT,POSTAL_CODE,CITY,...,PRODUCT_ID,CATEGORY,SUB_CATEGORY,PRODUCT_NAME,SALES,QUANTITY,DISCOUNT,PROFIT,SHIPPING_COST,ORDER_PRIORITY
16566,49187,ZA-2015-TS11205146-42062,2/27/2015,3/3/2015,Second Class,TS-11205146,Thomas Seio,Corporate,NaN,Ndola,...,TEC-AC-5226,Technology,Accessories,"Memorex Router, USB",$246.42,1,0,$19.71,20.62,Medium
9158,49186,ZA-2015-TS11205146-42062,2/27/2015,3/3/2015,Second Class,TS-11205146,Thomas Seio,Corporate,NaN,Ndola,...,FUR-CH-5409,Furniture,Chairs,"Novimex Steel Folding Chair, Set of Two",$337.92,4,0,$16.80,49.16,Medium
13144,50069,ZA-2015-SW10350146-42061,2/26/2015,3/3/2015,Standard Class,SW-10350146,Sean Wendt,Home Office,NaN,Lusaka,...,TEC-CO-4577,Technology,Copiers,"Hewlett Fax Machine, High-Speed",$318.12,1,0,$31.80,29.43,Medium
19586,50068,ZA-2015-SW10350146-42061,2/26/2015,3/3/2015,Standard Class,SW-10350146,Sean Wendt,Home Office,NaN,Lusaka,...,TEC-CO-3593,Technology,Copiers,"Brother Fax and Copier, High-Speed",$189.69,1,0,$37.92,13.85,Medium
31885,49681,ZA-2015-SM10005146-42241,8/25/2015,8/25/2015,Same Day,SM-10005146,Sally Matthias,Consumer,NaN,Chingola,...,OFF-FA-3071,Office Supplies,Fasteners,"Advantus Staples, Metal",$43.92,4,0,$18.00,3.84,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45598,48618,AE-2014-MY7380138-42004,12/31/2014,1/3/2015,Second Class,MY-7380138,Maribeth Yedwab,Corporate,NaN,Ras al Khaymah,...,OFF-SU-6166,Office Supplies,Supplies,"Stiletto Letter Opener, High Speed",$16.67,2,0.7,-$29.47,1.41,High
49172,47297,AE-2014-EB4110138-41926,10/14/2014,10/14/2014,Same Day,EB-4110138,Eugene Barchas,Consumer,NaN,Ras al Khaymah,...,OFF-FA-2945,Office Supplies,Fasteners,"Accos Paper Clips, Bulk Pack",$4.25,1,0.7,-$4.69,1.1,High
3754,47298,AE-2014-EB4110138-41926,10/14/2014,10/14/2014,Same Day,EB-4110138,Eugene Barchas,Consumer,NaN,Ras al Khaymah,...,FUR-BO-3647,Furniture,Bookcases,"Bush Stackable Bookrack, Pine",$224.75,6,0.7,-$232.27,60.08,High
31086,48313,AE-2012-PO8865138-41184,10/2/2012,10/6/2012,Standard Class,PO-8865138,Patrick O'Donnell,Consumer,NaN,Ajman,...,OFF-ST-4258,Office Supplies,Storage,"Fellowes File Cart, Industrial",$82.67,2,0.7,-$157.09,5.69,Medium
33207,48312,AE-2012-PO8865138-41184,10/2/2012,10/6/2012,Standard Class,PO-8865138,Patrick O'Donnell,Consumer,NaN,Ajman,...,TEC-MA-4190,Technology,Machines,"Epson Calculator, Red",$78.41,6,0.7,-$88.99,3.87,Medium

In [11]:
df.dtypes

ROW_ID            str
ORDER_ID          str
ORDER_DATE        str
SHIP_DATE         str
SHIP_MODE         str
CUSTOMER_ID       str
CUSTOMER_NAME     str
SEGMENT           str
POSTAL_CODE       str
CITY              str
STATE             str
COUNTRY           str
REGION            str
MARKET            str
PRODUCT_ID        str
CATEGORY          str
SUB_CATEGORY      str
PRODUCT_NAME      str
SALES             str
QUANTITY          str
DISCOUNT          str
PROFIT            str
SHIPPING_COST     str
ORDER_PRIORITY    str
dtype: object

# Data Tranformation

In [12]:
df.isna().sum()

ROW_ID                0
ORDER_ID              0
ORDER_DATE            0
SHIP_DATE             0
SHIP_MODE             0
CUSTOMER_ID           0
CUSTOMER_NAME         0
SEGMENT               0
POSTAL_CODE       41296
CITY                  0
STATE                 0
COUNTRY               0
REGION                0
MARKET                0
PRODUCT_ID            0
CATEGORY              0
SUB_CATEGORY          0
PRODUCT_NAME          0
SALES                 0
QUANTITY              0
DISCOUNT              0
PROFIT                0
SHIPPING_COST         0
ORDER_PRIORITY        0
dtype: int64

In [13]:
df["ROW_ID"] = df["ROW_ID"].astype(int)

In [14]:
df.ORDER_ID

0         IT-2014-VM2168591-41711
1        CA-2014-AS10045140-41727
2         ES-2013-DM1352548-41369
3        ES-2013-NM18520120-41634
4          IN-2014-LC168857-41747
                   ...
51285    CA-2012-TS21370140-41209
51286      ID-2013-BG110357-41276
51287    CA-2015-TS21370140-42283
51288    CA-2012-TS21370140-41209
51289    CA-2012-TS21370140-41209
Name: ORDER_ID, Length: 51290, dtype: str

In [15]:
df.ORDER_DATE

0         3/13/2014
1         3/29/2014
2          4/5/2013
3        12/26/2013
4         4/18/2014
            ...
51285    10/27/2012
51286      1/2/2013
51287     10/6/2015
51288    10/27/2012
51289    10/27/2012
Name: ORDER_DATE, Length: 51290, dtype: str

In [16]:
df["ORDER_DATE"] = pd.to_datetime(df["ORDER_DATE"])

In [17]:
df["ORDER_DATE"].isna().sum()

np.int64(0)

In [18]:
df["SHIP_DATE"] = pd.to_datetime(df["SHIP_DATE"])

In [19]:
df.SHIP_DATE.isna().sum()

np.int64(0)

In [20]:
df["SHIP_MODE"] = df["SHIP_MODE"].astype(str)

In [21]:
df.columns

Index(['ROW_ID', 'ORDER_ID', 'ORDER_DATE', 'SHIP_DATE', 'SHIP_MODE',
       'CUSTOMER_ID', 'CUSTOMER_NAME', 'SEGMENT', 'POSTAL_CODE', 'CITY',
       'STATE', 'COUNTRY', 'REGION', 'MARKET', 'PRODUCT_ID', 'CATEGORY',
       'SUB_CATEGORY', 'PRODUCT_NAME', 'SALES', 'QUANTITY', 'DISCOUNT',
       'PROFIT', 'SHIPPING_COST', 'ORDER_PRIORITY'],
      dtype='str')

In [22]:
df.POSTAL_CODE = df["POSTAL_CODE"].fillna(0)

In [23]:
df["SALES"] = (df["SALES"]
    .str.replace("$", '')
    .str.replace(",", '')
    .astype(float)
)

In [24]:
df.QUANTITY = df.QUANTITY.astype(int)

In [25]:
df.DISCOUNT = df.DISCOUNT.astype(float)

In [26]:

df["PROFIT"] = (df["PROFIT"]
    .str.replace("$", '')
    .str.replace(",", '')
    .astype(float)
    )

In [27]:
df['SHIPPING_COST'] = df['SHIPPING_COST'].astype(float)

In [28]:
df.head()

,ROW_ID,ORDER_ID,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,CUSTOMER_NAME,SEGMENT,POSTAL_CODE,CITY,...,PRODUCT_ID,CATEGORY,SUB_CATEGORY,PRODUCT_NAME,SALES,QUANTITY,DISCOUNT,PROFIT,SHIPPING_COST,ORDER_PRIORITY
0,11743,IT-2014-VM2168591-41711,2014-03-13,2014-03-13,Same Day,VM-2168591,Valerie Mitchum,Home Office,0,Bergen op Zoom,...,FUR-CH-5442,Furniture,Chairs,"Office Star Executive Leather Armchair, Black",2570.87,11,0.5,-2211.17,520.89,High
1,32648,CA-2014-AS10045140-41727,2014-03-29,2014-04-01,First Class,AS-100451408,Aaron Smayling,Corporate,22204,Arlington,...,OFF-ST-4516,Office Supplies,Storage,Hanging Personal Folder File,31.40,2,0.0,7.85,3.81,Medium
2,17522,ES-2013-DM1352548-41369,2013-04-05,2013-04-05,Same Day,DM-1352548,Don Miller,Corporate,0,Hanover,...,TEC-PH-3149,Technology,Phones,"Apple Smart Phone, with Caller ID",2875.77,9,0.5,-1783.08,516.63,High
3,14721,ES-2013-NM18520120-41634,2013-12-26,2013-12-28,Second Class,NM-18520120,Neoma Murray,Consumer,0,Vigo,...,FUR-BO-5948,Furniture,Bookcases,"Sauder Classic Bookcase, Metal",1741.80,4,0.0,261.24,515.24,Critical
4,29629,IN-2014-LC168857-41747,2014-04-18,2014-04-19,First Class,LC-168857,Lena Creighton,Consumer,0,Sydney,...,TEC-CO-6012,Technology,Copiers,"Sharp Wireless Fax, Laser",1601.64,5,0.1,587.19,511.47,Critical

In [29]:
df = df.drop('ORDER_ID', axis=1)
df = df.drop('CUSTOMER_ID', axis=1)
df = df.drop('PRODUCT_ID', axis=1)

In [30]:
df.shape

(51290, 21)

# Data Preparation

In [31]:
df["TOTAL_PRICE"] = (df['SALES'] * df['QUANTITY'])

In [32]:
df[['TOTAL_PRICE']]

       TOTAL_PRICE
0         28279.57
1            62.80
2         25881.93
3          6967.20
4          8008.20
...            ...
51285       707.00
51286        15.26
51287       351.20
51288        14.36
51289        12.56

[51290 rows x 1 columns]

In [33]:
df['BEST_SELLING'] = (
    df.groupby('PRODUCT_NAME')['QUANTITY']
      .transform('sum')
)

In [34]:
df[['PRODUCT_NAME','BEST_SELLING']].sort_values(by='BEST_SELLING', ascending=True)

                                            PRODUCT_NAME  BEST_SELLING
48456  Bush Saratoga Collection 5-Shelf Bookcase, Han...             1
16426              Boston 1900 Electric Pencil Sharpener             1
26657                Penpower WorldCard Pro Card Scanner             1
47736       Chromcraft Training Table, Adjustable Height             1
27174                                           Xerox 20             1
...                                                  ...           ...
39714                                            Staples           876
27830                                            Staples           876
13246                                            Staples           876
25302                                            Staples           876
8605                                             Staples           876

[51290 rows x 2 columns]

In [35]:
df['COUNTRY_RANK'] = (df.groupby('COUNTRY')['TOTAL_PRICE']
                      .rank(method="dense", ascending=False))

In [36]:
(df[['COUNTRY','COUNTRY_RANK']].sort_values(by='COUNTRY_RANK')).head(10)

                     COUNTRY  COUNTRY_RANK
91                     China           1.0
23513              Sri Lanka           1.0
752    Republic of the Congo           1.0
3301                 Ukraine           1.0
302                Argentina           1.0
1265                 Algeria           1.0
327                  Lesotho           1.0
65            United Kingdom           1.0
969                    Ghana           1.0
12174                  Spain           1.0

In [37]:
df['YEAR'] = df['ORDER_DATE'].dt.year

In [38]:
df['DAY_NAME'] = df['ORDER_DATE'].dt.day_name()

In [39]:
df['DELIVERY_DAYS'] = df['SHIP_DATE'] - df['ORDER_DATE']

In [40]:
df['COUNTRY_RANK'] = df['COUNTRY_RANK'].astype(str)

In [41]:
df['DATE_ID'] = df.index
df['PAYMENT_ID'] = df.index
df['PRODUCT_ID'] = df.index
df['CUSTOMER_ID'] = df.index

In [42]:
df

,ROW_ID,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_NAME,SEGMENT,POSTAL_CODE,CITY,STATE,COUNTRY,...,TOTAL_PRICE,BEST_SELLING,COUNTRY_RANK,YEAR,DAY_NAME,DELIVERY_DAYS,DATE_ID,PAYMENT_ID,PRODUCT_ID,CUSTOMER_ID
0,11743,2014-03-13,2014-03-13,Same Day,Valerie Mitchum,Home Office,0,Bergen op Zoom,North Brabant,Netherlands,...,28279.57,89,1.0,2014,Thursday,0 days,0,0,0,0
1,32648,2014-03-29,2014-04-01,First Class,Aaron Smayling,Corporate,22204,Arlington,Virginia,United States,...,62.80,17,4817.0,2014,Saturday,3 days,1,1,1,1
2,17522,2013-04-05,2013-04-05,Same Day,Don Miller,Corporate,0,Hanover,Lower Saxony,Germany,...,25881.93,38,5.0,2013,Friday,0 days,2,2,2,2
3,14721,2013-12-26,2013-12-28,Second Class,Neoma Murray,Consumer,0,Vigo,Galicia,Spain,...,6967.20,69,49.0,2013,Thursday,2 days,3,3,3,3
4,29629,2014-04-18,2014-04-19,First Class,Lena Creighton,Consumer,0,Sydney,New South Wales,Australia,...,8008.20,63,136.0,2014,Friday,1 days,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,35143,2012-10-27,2012-10-30,First Class,Todd Sumrall,Corporate,90049,Los Angeles,California,United States,...,707.00,34,2087.0,2012,Saturday,3 days,51285,51285,51285,51285
51286,25579,2013-01-02,2013-01-06,Standard Class,Barry Gonzalez,Consumer,0,Brisbane,Queensland,Australia,...,15.26,89,2426.0,2013,Wednesday,4 days,51286,51286,51286,51286
51287,37635,2015-10-06,2015-10-10,Standard Class,Todd Sumrall,Corporate,10035,New York City,New York,United States,...,351.20,27,2874.0,2015,Tuesday,4 days,51287,51287,51287,51287
51288,35139,2012-10-27,2012-10-30,First Class,Todd Sumrall,Corporate,90049,Los Angeles,California,United States,...,14.36,71,5795.0,2012,Saturday,3 days,51288,51288,51288,51288
51289,35140,2012-10-27,2012-10-30,First Class,Todd Sumrall,Corporate,90049,Los Angeles,California,United States,...,12.56,9,5850.0,2012,Saturday,3 days,51289,51289,51289,51289

# Fact and Dimension Schema 
* Dimension Table

In [43]:
df.columns

Index(['ROW_ID', 'ORDER_DATE', 'SHIP_DATE', 'SHIP_MODE', 'CUSTOMER_NAME',
       'SEGMENT', 'POSTAL_CODE', 'CITY', 'STATE', 'COUNTRY', 'REGION',
       'MARKET', 'CATEGORY', 'SUB_CATEGORY', 'PRODUCT_NAME', 'SALES',
       'QUANTITY', 'DISCOUNT', 'PROFIT', 'SHIPPING_COST', 'ORDER_PRIORITY',
       'TOTAL_PRICE', 'BEST_SELLING', 'COUNTRY_RANK', 'YEAR', 'DAY_NAME',
       'DELIVERY_DAYS', 'DATE_ID', 'PAYMENT_ID', 'PRODUCT_ID', 'CUSTOMER_ID'],
      dtype='str')

### Customer Dimension

In [44]:
Customers = (
    df[[
        'CUSTOMER_ID',
        'CUSTOMER_NAME',
        'SEGMENT',
        'POSTAL_CODE',
        'CITY',
        'STATE',
        'COUNTRY',
        'REGION',
        'MARKET',
        'COUNTRY_RANK'
    ]]
    
)
Customers

,CUSTOMER_ID,CUSTOMER_NAME,SEGMENT,POSTAL_CODE,CITY,STATE,COUNTRY,REGION,MARKET,COUNTRY_RANK
0,0,Valerie Mitchum,Home Office,0,Bergen op Zoom,North Brabant,Netherlands,Western Europe,Europe,1.0
1,1,Aaron Smayling,Corporate,22204,Arlington,Virginia,United States,Southern US,USCA,4817.0
2,2,Don Miller,Corporate,0,Hanover,Lower Saxony,Germany,Western Europe,Europe,5.0
3,3,Neoma Murray,Consumer,0,Vigo,Galicia,Spain,Southern Europe,Europe,49.0
4,4,Lena Creighton,Consumer,0,Sydney,New South Wales,Australia,Oceania,Asia Pacific,136.0
...,...,...,...,...,...,...,...,...,...,...
51285,51285,Todd Sumrall,Corporate,90049,Los Angeles,California,United States,Western US,USCA,2087.0
51286,51286,Barry Gonzalez,Consumer,0,Brisbane,Queensland,Australia,Oceania,Asia Pacific,2426.0
51287,51287,Todd Sumrall,Corporate,10035,New York City,New York,United States,Eastern US,USCA,2874.0
51288,51288,Todd Sumrall,Corporate,90049,Los Angeles,California,United States,Western US,USCA,5795.0
51289,51289,Todd Sumrall,Corporate,90049,Los Angeles,California,United States,Western US,USCA,5850.0

In [45]:
Customers.dtypes

CUSTOMER_ID       int64
CUSTOMER_NAME       str
SEGMENT             str
POSTAL_CODE      object
CITY                str
STATE               str
COUNTRY             str
REGION              str
MARKET              str
COUNTRY_RANK        str
dtype: object

In [46]:
dim_product = (
    df[[
        'PRODUCT_ID',
        'PRODUCT_NAME',
        'CATEGORY',
        'SUB_CATEGORY',
        'ORDER_PRIORITY',
        'BEST_SELLING',
        'QUANTITY',
        'SHIP_MODE'
    ]]
)

dim_product

,PRODUCT_ID,PRODUCT_NAME,CATEGORY,SUB_CATEGORY,ORDER_PRIORITY,BEST_SELLING,QUANTITY,SHIP_MODE
0,0,"Office Star Executive Leather Armchair, Black",Furniture,Chairs,High,89,11,Same Day
1,1,Hanging Personal Folder File,Office Supplies,Storage,Medium,17,2,First Class
2,2,"Apple Smart Phone, with Caller ID",Technology,Phones,High,38,9,Same Day
3,3,"Sauder Classic Bookcase, Metal",Furniture,Bookcases,Critical,69,4,Second Class
4,4,"Sharp Wireless Fax, Laser",Technology,Copiers,Critical,63,5,First Class
...,...,...,...,...,...,...,...,...
51285,51285,Eldon Portable Mobile Manager,Office Supplies,Storage,High,34,5,First Class
51286,51286,"Cameo Business Envelopes, Security-Tint",Office Supplies,Envelopes,Medium,89,1,Standard Class
51287,51287,Samsung HM1900 Bluetooth Headset,Technology,Phones,Medium,27,4,Standard Class
51288,51288,Avery Non-Stick Binders,Office Supplies,Binders,High,71,2,First Class
51289,51289,Serrated Blade or Curved Handle Hand Letter Op...,Office Supplies,Supplies,High,9,2,First Class

In [47]:
df.columns

Index(['ROW_ID', 'ORDER_DATE', 'SHIP_DATE', 'SHIP_MODE', 'CUSTOMER_NAME',
       'SEGMENT', 'POSTAL_CODE', 'CITY', 'STATE', 'COUNTRY', 'REGION',
       'MARKET', 'CATEGORY', 'SUB_CATEGORY', 'PRODUCT_NAME', 'SALES',
       'QUANTITY', 'DISCOUNT', 'PROFIT', 'SHIPPING_COST', 'ORDER_PRIORITY',
       'TOTAL_PRICE', 'BEST_SELLING', 'COUNTRY_RANK', 'YEAR', 'DAY_NAME',
       'DELIVERY_DAYS', 'DATE_ID', 'PAYMENT_ID', 'PRODUCT_ID', 'CUSTOMER_ID'],
      dtype='str')

In [48]:
dim_date = (
    df[[
        'DATE_ID',
        'ORDER_DATE',
        'SHIP_DATE',
        'YEAR',
        'DAY_NAME',
        'DELIVERY_DAYS',
        'SHIPPING_COST',
        
    ]]
)
dim_date

,DATE_ID,ORDER_DATE,SHIP_DATE,YEAR,DAY_NAME,DELIVERY_DAYS,SHIPPING_COST
0,0,2014-03-13,2014-03-13,2014,Thursday,0 days,520.89
1,1,2014-03-29,2014-04-01,2014,Saturday,3 days,3.81
2,2,2013-04-05,2013-04-05,2013,Friday,0 days,516.63
3,3,2013-12-26,2013-12-28,2013,Thursday,2 days,515.24
4,4,2014-04-18,2014-04-19,2014,Friday,1 days,511.47
...,...,...,...,...,...,...,...
51285,51285,2012-10-27,2012-10-30,2012,Saturday,3 days,14.96
51286,51286,2013-01-02,2013-01-06,2013,Wednesday,4 days,1.20
51287,51287,2015-10-06,2015-10-10,2015,Tuesday,4 days,4.69
51288,51288,2012-10-27,2012-10-30,2012,Saturday,3 days,1.57
51289,51289,2012-10-27,2012-10-30,2012,Saturday,3 days,1.41

In [49]:
dim_Payments = (
    df[[
        'PAYMENT_ID',
        'SALES',
        'PROFIT',
        'DISCOUNT',
        'TOTAL_PRICE'
    ]]
)
dim_Payments.head()

   PAYMENT_ID    SALES   PROFIT  DISCOUNT  TOTAL_PRICE
0           0  2570.87 -2211.17       0.5     28279.57
1           1    31.40     7.85       0.0        62.80
2           2  2875.77 -1783.08       0.5     25881.93
3           3  1741.80   261.24       0.0      6967.20
4           4  1601.64   587.19       0.1      8008.20

## Fact Table

In [50]:
df.columns

Index(['ROW_ID', 'ORDER_DATE', 'SHIP_DATE', 'SHIP_MODE', 'CUSTOMER_NAME',
       'SEGMENT', 'POSTAL_CODE', 'CITY', 'STATE', 'COUNTRY', 'REGION',
       'MARKET', 'CATEGORY', 'SUB_CATEGORY', 'PRODUCT_NAME', 'SALES',
       'QUANTITY', 'DISCOUNT', 'PROFIT', 'SHIPPING_COST', 'ORDER_PRIORITY',
       'TOTAL_PRICE', 'BEST_SELLING', 'COUNTRY_RANK', 'YEAR', 'DAY_NAME',
       'DELIVERY_DAYS', 'DATE_ID', 'PAYMENT_ID', 'PRODUCT_ID', 'CUSTOMER_ID'],
      dtype='str')

In [51]:
Fact_table = (
    df[[
        'ROW_ID',
        'CUSTOMER_ID',
        'PRODUCT_ID',
        'DATE_ID',
        'PAYMENT_ID'
    ]]
)
Fact_table.head()

   ROW_ID  CUSTOMER_ID  PRODUCT_ID  DATE_ID  PAYMENT_ID
0   11743            0           0        0           0
1   32648            1           1        1           1
2   17522            2           2        2           2
3   14721            3           3        3           3
4   29629            4           4        4           4

In [52]:
Customers.to_csv("CUSTOMERS.csv", index=False)
dim_date.to_csv("DATES.csv", index=False)
dim_product.to_csv("PRODUCTS.csv", index=False)
dim_Payments.to_csv("PAYMENTS.csv", index=False)

## Data lead

In [53]:
def table_exists(cur, table_name):
    cur.execute("""
        SELECT count(*)
        FROM all_tables
        where table_name = :table_name
        """, [table_name.upper()]
    )
    return cur.fetchone()[0] == 1

In [54]:
cur.execute("drop table Customers")
conn.commit
print("droped")

droped

In [55]:
cur.execute(
    """
select table_name 
from all_tables
where owner = 'HR'
"""
)
for t in cur.fetchall():
    print(t[0])

REGIONS
COUNTRIES
LOCATIONS
DEPARTMENTS
JOBS
EMPLOYEES
JOB_HISTORY
TALIB
EMP1
GLOBAL_SUPERSTORE2
DATES
PAYMENTS

In [56]:
if not table_exists(cur, 'CUSTOMERS'):
    cur.execute("""
        CREATE TABLE CUSTOMERS (
                CUSTOMER_ID NUMBER(10) PRIMARY KEY,
                CUSTOMER_NAME VARCHAR2(100),
                SEGMENT VARCHAR2(50),
                POSTAL_CODE NUMBER(10),
                CITY VARCHAR2(50),
                STATE VARCHAR2(50),
                COUNTRY VARCHAR2(80),
                REGION VARCHAR2(50),
                MARKET VARCHAR2(50),
                COUNTRY_RANK FLOAT(10)
            
        )
        """)
    print("Table Created ")
else :
    print("Table Already Exist")
conn.commit()

Table Created

In [57]:
cur.execute("""
    select table_name
            from all_tables
            where owner = 'HR'
""")

for t in cur.fetchall():
    print(t[0])

REGIONS
COUNTRIES
LOCATIONS
DEPARTMENTS
JOBS
EMPLOYEES
JOB_HISTORY
TALIB
EMP1
GLOBAL_SUPERSTORE2
DATES
PAYMENTS
CUSTOMERS

In [58]:
if not table_exists(cur, "DATES"):
    cur.execute("""
        CREATE TABLE DATES(
                DATE_ID NUMBER PRIMARI KEY,
                ORDER_DATE DATE,
                SHIP_DATE DATE,
                YEAR NUMBER(4),
                DAY_NAME VARCHAR2(20),
                DELIVERY_DAYS TIMESTAMP,
                SHIPPING_COST FLOAT
            )
            """
    )
    print("Table Created")

else:
    print("Table Already Exists")

Table Already Exists

In [59]:
if not table_exists(cur, "PAYMENTS"):
    cur.execute("""
        CREATE TABLE PAYMENTS(
                PAYMENT_ID NUMBER )"""
    )